### ISSUE TITLE
overrides

### ISSUE THREAD

**Issue by unicomp21** [Blimster/babylon_dart#10]
@JS()
class MyParticleSystem extends SolidParticleSystem {
  final particle_count = 64;

  external MyParticleSystem(String name, Scene scene) : super(name, scene) {
    final box = Mesh.CreateBox('box', 1.0);
    addShape(box, particle_count);
  }
  @override
  void initParticles() {
    var index = 0;
    for(var v in dimensional.neighbor_dimensions_iterate(3, 3, false)) {
      assert(index < particle_count);
      final particle = getParticleById(index);
      particle.position = Vector3(v.x, v.y, v.z);
      index++;
    }
  }
  @override
  SolidParticleSystem updateParticleVertex(SolidParticle particle, SolidParticleVertex vertex, num pt)
  {
    return this;
  }
}

**Comment by unicomp21** [comment]
Getting compile errors on the overrides, and am starting to think the inherit/override pattern can't be supported w/ JS interop?

**Comment by unicomp21** [comment]
The reason I ask, I have a need to animate vertex color, and vertex position from updateParticleVertex.

**Comment by Blimster** [comment]
Yes, it is not a good idea to extend classes from the package. I think a better way is to generate updateParticleVertex not as a method but as a getter/setter pair. I'm currently working on a complete rewrite of the generator. I will consider this.
