### ISSUE TITLE
Noise editor functionality

### ISSUE THREAD

**Issue by unicomp21** [Blimster/babylon_dart#12]
https://github.com/BabylonJS/Babylon.js/blob/107db4e0775b6774746a7456a72eae86bfc4d849/dist/nodeEditor/babylon.nodeEditor.module.d.ts

not sure this one is doable, but it's a pretty powerful concept

wonder if transpiling typescript into dart might be possible someday.  jsii is starting to look interesting.

**Comment by Blimster** [comment]
I looked into it and I think this is doable. But I'm a little bit short of time at the moment. Hopefully, this has no a high prio for you.

**Comment by unicomp21** [comment]
Not high at all.  Can use original babylon editor in the meantime.
