### ISSUE TITLE
4.2

### ISSUE THREAD

**Issue by unicomp21** [Blimster/babylon_dart#2]
Does this cover 4.2 yet?  Dying to try the new SPS vertex color updates.

**Comment by unicomp21** [comment]
BTW, this is awesome!!!

**Comment by Blimster** [comment]
I already read on Twitter that Babylon 4.2 is on the way. I will switch to that version after it is officially released.

**Comment by unicomp21** [comment]
Can't wait!

**Comment by unicomp21** [comment]
@Blimster where is the conversion script?  I'm wondering if we could try running it on google filament as well?

https://github.com/google/filament/issues/3076#event-3807155753

**Comment by Blimster** [comment]
Yes, there is a companion project [babylon_dart_gen](https://github.com/blimster/babylon_dart_gen). It contains code to generate Dart sources from a Typescript definition file. The focus is to generate Dart sources for the complete babylon.d.ts file. But it is designed with the idea to have an alternative for js_facade_gen, because js_facade_gen failed on babylon.d.ts. My current plan is to complete the work on Babylon and maybe then create a more general version of babylon_dart_gen.

I looked into the definition file for google filament and I have to say that it will currently not be possible to generate working Dart bindings for that.

**Comment by unicomp21** [comment]
Thanks for looking!

Thinking out loud here.  If we assumed all generated dart code is "async", I'm wondering if it would be easier to "generate" a marshaling layer (similar to grpc, but custom) into the typescript calls.  There would need to be correlation_id's for each call, etc.  Still thinking it thru, not sure if it would be easier or not.

**Comment by Blimster** [comment]
What do you mean by "if we assumed all generated dart code is async"?

**Comment by unicomp21** [comment]
Every return type for the generated/marshaled dart api, which call the typescript, returns a Future<> or Stream<>

**Comment by unicomp21** [comment]
The idea would be to generate a remote procedure call api, the resulting messages would go into a memory ring for ipc between (processes or threads or coroutines)

**Comment by unicomp21** [comment]
I'm definitely not an expert.  But, seems to me.  If a .d.ts can be generated from javascript, it should also be possible to generate the serde plumbing code to rpc each part of an api (ie typescript and dart code)

>>Getting the DTS from a JavaScript file
https://github.com/microsoft/TypeScript/wiki/Using-the-Compiler-API

**Comment by Blimster** [comment]
I am generating Dart code by reading a .d.ts file using the TypeScript Compiler API. I don't know why you want that RPC think, when it possible to generate the code JS bindings directly. RPC would be a large performance issue.

**Comment by unicomp21** [comment]
Very good point on the performance argument.  But, if the rpc bindings could "batch" the serialized calls into cpu primitive data types, using large ArrayBuffer's, I'm tempted to think it might be possible to exceed the performance of direct bindings.  And one would also have the added flexibility of using "event bus" patterns.  Though, I should stop pontificating, your stuff works and I got nothing, at this point.

**Comment by unicomp21** [comment]
Looks like 4.2 is out, any thoughts on SPS?

**Comment by OliverDamm** [comment]
In the newest version of babylon_dart, BabylonJS 4.2 is in use. But I didn't do any work on SPS. 

I am not deep inside the topic. Can you give a list of classes, interfaces, etc. you require for your work? Then I will start to add the bindings.

**Comment by unicomp21** [comment]
https://github.com/BabylonJS/Babylon.js/blob/c5ad71f1737bea156a1cbe91f693640ae327ad6b/src/Particles/solidParticleSystem.ts

**Comment by unicomp21** [comment]
not a high priority

**Comment by Blimster** [comment]
I added bindings for SPS. There is also a dedicated example for SPS.

Have fun.

**Comment by unicomp21** [comment]
Thanks Oliver!

**Comment by unicomp21** [comment]
@rhulha take a peek over here!  Pretty amazing eh?

**Comment by rhulha** [comment]
Is there a demo online ?

**Comment by unicomp21** [comment]
@rhulha Do a git clone and check out the examples folder.

**Comment by unicomp21** [comment]
Use
dart webdev serve (flutter install)
or just
webdev serve
