### ISSUE TITLE
import babylon_dart

### ISSUE THREAD

**Issue by unicomp21** [Blimster/babylon_dart#3]
when i import babylon_dart, can't seem to get it working

could we get an external git repo w/ a working example importing babylong_dart?

---
name: LPS_html
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  js: ^0.6.2
  path: ^1.7.0
  babylon_dart: ^0.7.0

dev_dependencies:
  build_runner: ^1.10.0
  build_web_compilers: ^2.11.0
  pedantic: ^1.9.0

**Comment by Blimster** [comment]
Can you provide more details of your problem?

**Comment by Blimster** [comment]
I just saw, that the links to the BabylonJS implementation were not update-to-date in the README.md. Maybe, this is your problem?

**Comment by unicomp21** [comment]
Yep, that must be the problem, thanks.
