### ISSUE TITLE
Null Engine support

### ISSUE THREAD

**Issue by unicomp21** [Blimster/babylon_dart#8]
Starting to realize NullEngine support would be useful when writing utilities which run outside the browser.

https://github.com/BabylonJS/Babylon.js/blob/a644f1526bf93e2e27beb64276a7ebe22f1d1d36/src/Engines/nullEngine.ts

**Comment by Blimster** [comment]
Version 0.8.0 (and 1.0.0-nullsafety.1 for the case you already use null safety) is out.
